backend:
  name: git-gateway
  branch: main

media_folder: "public"
public_folder: "/"

collections:
  - name: "crochet"
    label: "Crochet Creations"
    folder: "src/content/crochet"
    create: true
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Price (₹)", name: "price", widget: "number"}
      - {label: "Product Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Snipcart ID", name: "snipcart_id", widget: "string"}